/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AgentBRouteImport } from './routes/agent-b'
import { Route as AgentARouteImport } from './routes/agent-a'
import { Route as IndexRouteImport } from './routes/index'

const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentBRoute = AgentBRouteImport.update({
  id: '/agent-b',
  path: '/agent-b',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentARoute = AgentARouteImport.update({
  id: '/agent-a',
  path: '/agent-a',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-a': typeof AgentARoute
  '/agent-b': typeof AgentBRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-a': typeof AgentARoute
  '/agent-b': typeof AgentBRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-a': typeof AgentARoute
  '/agent-b': typeof AgentBRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-a' | '/agent-b' | '/demo' | '/docs' | '/protocol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-a' | '/agent-b' | '/demo' | '/docs' | '/protocol'
  id:
    | '__root__'
    | '/'
    | '/agent-a'
    | '/agent-b'
    | '/demo'
    | '/docs'
    | '/protocol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentARoute: typeof AgentARoute
  AgentBRoute: typeof AgentBRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  ProtocolRoute: typeof ProtocolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-b': {
      id: '/agent-b'
      path: '/agent-b'
      fullPath: '/agent-b'
      preLoaderRoute: typeof AgentBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-a': {
      id: '/agent-a'
      path: '/agent-a'
      fullPath: '/agent-a'
      preLoaderRoute: typeof AgentARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentARoute: AgentARoute,
  AgentBRoute: AgentBRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  ProtocolRoute: ProtocolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
